### ISSUE TITLE
set up central "arax-response-registry" MySQL database instance for ARAX response tracking and an associated S3 bucket for response JSON

### ISSUE THREAD

**Issue by saramsey** [RTXteam/RTX#1702]
- [x] Create a branch in RTX for working on this issue
- [x] Create a new subdirectory `arax-response-registry` of `DockerBuild` for the code within the branch
- [x] Estimate instance size requirements
- [x] Create instance `arax-response-registry.rtx.ai` or some such, with elastic IP address and DNS configuration
- [x] install @edeutsch and @finnagin RSA public keys into the instance
- [x] Dockerfile for setting up MySQL in Ubuntu 20.04
- [x] Have @finnagin look over the Dockerfile for correctness
- [x] Install Docker into the instance (via shell script that is in the RTX repo that is pulled into the host OS via `git checkout`) 
- [x] build the Docker image using the Dockerfile
- [x] create the MySQL container from the docker image, with port mapping for the mysql client port
- [x] run mysql inside the container
- [x] via a shell script (?) that is tracked in the GitHub repo, create empty database and a mysql user account with full CRUD access to the database from external network IP addresses
- [x] Create IAM user for read/write access to *only* the `arax-response-storage` S3 bucket in `us-west-2`
- [x] Pass mysql credentials and the AWS credentials to @edeutsch for testing
- [x] Document how to reproduce the `arax-response-registry` server (from scratch) in `DockerBuild/arax-response-registry/README.md`

**Comment by saramsey** [comment]
Branch for the coding work on this issue is [issue-1702](https://github.com/RTXteam/RTX/tree/issue-1702)

**Comment by saramsey** [comment]
Hi @edeutsch any thoughts on requirements for the mysql instance, in terms of storage?

**Comment by saramsey** [comment]
Can we close this issue out?

**Comment by edeutsch** [comment]
I don't know. There are some unckecked tasks still. I am uncertain if they've been done. Maybe we could document where if they have?

**Comment by finnagin** [comment]
I can go through those unchecked boxes and make sure they got done then close when I've either verified each one is done or finished them if they were not done.
