### ISSUE TITLE
Improve ARAX's ranking algorithm

### ISSUE THREAD

**Issue by chunyuma** [RTXteam/RTX#2299]
This is a super issue for "Better Ranking". I split it into the following few sub-tasks:

- [x] Adjust weights in the [ranker](https://github.com/RTXteam/RTX/blob/master/code/ARAX/ARAXQuery/ARAX_ranker.py#L205-L225). See the sub-task in #2300.
- [x] Add a function in ranker to give higher weight based on the number of edges. See the sub-task in https://github.com/RTXteam/RTX/issues/2301.
- [x] Gather examples and write a few test cases for evaluation. See the sub-task in https://github.com/RTXteam/RTX/issues/2302.
- [x] Final evaluation after deployment.

**Comment by dkoslicki** [comment]
And from last week's AHM, here is a rough idea for specific ways to help improve the ranker:
>Non-semmeddb direct “treats” should be ranked higher
More edges is better
	Downweight text mining provider
	Downweight semmeddb
	Single drugbank edge better than multiple textmined edges

>Gather examples in gold, silver, bronze, tin (handful, ~10)
Set up test harness of these examples
	Load the results (no need to recompute)
	Re-rank
	Reassess 
	Tweak, itterate

**Comment by chunyuma** [comment]
Keep this issue open until we have verified its effect in deployment.

**Comment by chunyuma** [comment]
Based on [recent evaluation report](https://github.com/RTXteam/RTX/issues/2324#issuecomment-2307603412) from Eric, the new ARAX's ranking algorithm looks great. So, I close this issue.
